version: "3"
services:
  calc:
    build:
      context: ./node-calc
      dockerfile: ./Dockerfile
    container_name: CALC
    image: node-calc
    ports:
      - "8080:8080"
    networks:
      calcnet:
        ipv4_address: 172.19.0.100

  postfix:
    build:
      context: ./node-postfix
      dockerfile: ./Dockerfile
    container_name: POSTIX
    image: node-postfix
    ports:
      - "9090:9090"  
    networks:
      calcnet:
        ipv4_address: 172.19.0.200

  add:
    build:
      context: ./node-add
      dockerfile: ./Dockerfile 
    container_name: ADD
    image: node-add
    ports:
      - "8081:8081"  
    networks:
      calcnet:
        ipv4_address: 172.19.10.1

  subtract:
    build:
      context: ./node-subtract
      dockerfile: ./Dockerfile 
    container_name: SUBTRACT
    image: node-subtract
    ports:
      - "8082:8082"  
    networks:
      calcnet:
        ipv4_address: 172.19.10.2

  multiply:
    build:
      context: ./node-multiply
      dockerfile: ./Dockerfile
    container_name: MULTIPLY
    image: node-multiply
    ports:
      - "8083:8083"  
    networks:
      calcnet:
        ipv4_address: 172.19.10.3

  divide:
    build:
      context: ./node-divide
      dockerfile: ./Dockerfile
    container_name: DIVIDE
    image: node-divide
    ports:
      - "8084:8084"  
    networks:
      calcnet:
        ipv4_address: 172.19.10.4

  power:
    build:
      context: ./node-power
      dockerfile: ./Dockerfile
    container_name: POWER
    image: node-power
    ports:
      - "8085:8085"  
    networks:
      calcnet:
        ipv4_address: 172.19.10.5

networks:
  calcnet:
    driver: macvlan
    driver_opts:
          parent: lo0
    ipam:
      config:
        - subnet: 172.19.0.0/16