version: "3"
services:
  calc:
    build:
      context: ./node-calc
      dockerfile: ./Dockerfile
    depends_on:
      - add
      - subtract
      - multiply
      - divide
      - power
      - postfix
    container_name: CALC
    image: node-calc
    ports:
      - "8080:8080"

  postfix:
    build:
      context: ./node-postfix
      dockerfile: ./Dockerfile
    container_name: POSTIX
    image: node-postfix
    ports:
      - "9090:9090"  

  add:
    build:
      context: ./node-add
      dockerfile: ./Dockerfile 
    container_name: ADD
    image: node-add
    ports:
      - "8081:8081"  

  subtract:
    build:
      context: ./node-subtract
      dockerfile: ./Dockerfile 
    container_name: SUBTRACT
    image: node-subtract
    ports:
      - "8082:8082"  

  multiply:
    build:
      context: ./node-multiply
      dockerfile: ./Dockerfile
    container_name: MULTIPLY
    image: node-multiply
    ports:
      - "8083:8083"  

  divide:
    build:
      context: ./node-divide
      dockerfile: ./Dockerfile
    container_name: DIVIDE
    image: node-divide
    ports:
      - "8084:8084"  

  power:
    build:
      context: ./node-power
      dockerfile: ./Dockerfile
    container_name: POWER
    image: node-power
    ports:
      - "8085:8085"  