{
  "kind": "Service",
  "apiVersion": "v1",
  "metadata": {
    "name": "node-power",
    "namespace": "default",
    "selfLink": "/api/v1/namespaces/default/services/node-power",
    "resourceVersion": "147845",
    "creationTimestamp": "2017-12-16T12:10:43Z",
    "labels": {
      "run": "node-power"
    }
  },
  "spec": {
    "ports": [
      {
        "protocol": "TCP",
        "port": 8085,
        "targetPort": 8085
      }
    ],
    "selector": {
      "run": "node-power"
    },
    "clusterIP": "172.19.10.5",
    "type": "ClusterIP",
    "sessionAffinity": "None"
  },
  "status": {
    "loadBalancer": {}
  }
}